### ISSUE TITLE
More filters (e.g., ore per minute < X, ETD < Y)

### ISSUE THREAD

**Issue by wchristian** [narc0tiq/YARM#117] opened 2019-05-14 15:06 UTC
Right now the filtered view is limited to percentage only, but the ore per minute value is more stable now, and might be a more useful filter for deciding which deposits to show in the small list.

**Comment by narc0tiq** [comment] 2019-05-15 08:33
More filters are definitely a good wishlist item; I'm not entirely sure which way an ore-per-minute filter would go -- show only sites not being mined/not mining fast enough?

But really, the main difficulty in adding more filters is making buttons for them. What I want to see are options for:
- no sites (exists)
- remaining % < configurable % (exists, but named "warnings")
- ETD < configurable number of minutes/hours
- all warnings (composite of the warning states from above)
- only sites with finite products (i.e., regular ores)
- only sites with infinite products (i.e., oil, or some mod ores)
- all sites (exists)
- ore summary (#8)

We could also slot in 'ore per minute < configurable' somewhere in there, but I'm not sure if it would be included in the 'warnings' filter.

**Comment by wchristian** [comment] 2019-05-16 09:42
I targeted the wrong variable, was indeed looking for ETD, but i'm honestly on board with simply making it more filters. :)

**Comment by proegssilb** [comment] 2019-06-11 06:41
A great starting point for this would be to simply have a mod setting for changing the % warning level, but adding a warning mode for "ETD < [threshold]" would be pretty handy too.

One use case for based on ore per minute would be filtering out sites that have been scanned (And therefore labeled on the map), but aren't hooked up yet; if no resources being mined, don't show. The flip side use case would be "Make sure my highest-traffic mines are always visible so I know how close they are to needing replacement."

**Comment by narc0tiq** [comment] 2024-11-19 21:59
I'm going through all the issues right now and I've realized this is a differently-phrased duplicate of #11, currently planned as a stretch goal for the upcoming 1.0 release; I would like to direct any further discussion to there

**Closed by narc0tiq** 2024-11-19 21:59 UTC
Labels: enhancement
