### ISSUE TITLE
"Do It" button accept enter key

### ISSUE THREAD

**Issue by ChuckSavage** [narc0tiq/YARM#75] opened 2018-03-31 02:39 UTC
I think the title says it all. Anyway, a little more detail:

When editing a site name, after adjusting it however one wants, to be able to use the "enter" key to finalize the input instead of having to use the mouse to click the "Do It" button.

**Comment by ChuckSavage** [comment] 2018-03-31 02:40
I suppose, using the Escape key to cancel would be along the same lines.

**Comment by narc0tiq** [comment] 2019-03-23 22:07
Version 0.8 has the latter (on the same note, opening an entity GUI also closes the rename GUI now), but the enter key isn't as easy. Nonetheless, it's on my wishlist.

**Comment by narc0tiq** [comment] 2024-11-19 20:36
Resolved in the 1.0 refactor, it turns out I only needed to handle `on_gui_confirmed`

**Closed** 2024-11-19 20:37 UTC
Labels: enhancement
